### ISSUE TITLE
Repository can be renamed to `julia-bindings`

### ISSUE THREAD

**Issue by IshaanDesai** [pavelkharitenko/julia-bindings#1]
If the naming convention of other language bindings is to be followed, for example the [python-bindings](https://github.com/precice/python-bindings), this repository and the project being developed can be named `julia-bindings`

**Comment by pavelkharitenko** [comment]
Thank you for the hint. We can of course name the repository itself it how the preCICE community wants it to be, but I just want to make clear that the naming `projectname/PackageName.jl` is a community and developer-wide convention for all Julia packages, that are on the general repository but it appears also the same for their corresponding github pages. See the point 6. in the naming guidelines https://pkgdocs.julialang.org/v1/creating-packages/#Package-naming-guidelines 

So its preCICE convention vs Julia convention. If you have already considered this, then we can proceed with `julia-bindings`.

**Comment by IshaanDesai** [comment]
Thanks for the information, it already helps to have a naming convention from the Julia side. We can stick to it for now. As for the current name, I understand it as preCICE + C bindings correct? 
One more tip: it is really stressed that the "p" in preCICE is lower case :smile:

**Comment by pavelkharitenko** [comment]
I think talking about the naming is a bit too early because of the following reasons: 
This repo name exists only to distinguis it from the CxxWrap.jl solution one, hence the final C in PreCICEC. When we decide which one we should pick, I would name the final Julia package "PreCICE.jl" for the General package repository of Julia, and we can still name the github repository "julia-bindings". 
And yes, unfortunately all Julia's module names are UpperCamelCase, but if we insist, i think preCICE.jl would not break anything. But since we export all functions now, Users will only have to put `using PreCICE` and can use all the function without the `PreCICE.-` prefix, so it would hurt the eye only once... 😄

**Comment by IshaanDesai** [comment]
> I think talking about the naming is a bit too early because of the following reasons:

Getting the right name would make it easier when we eventually integrate this repo into the preCICE project, so its never too early to get the name right :wink: 

> This repo name exists only to distinguish it from the CxxWrap.jl solution one, hence the final C in PreCICEC. When we decide which one we should pick, I would name the final Julia package "PreCICE.jl" for the General package repository of Julia, and we can still name the github repository "julia-bindings".

This makes sense, having the repository name as `julia-bindings` and the package name as `PreCICE.jl`.

> And yes, unfortunately all Julia's module names are UpperCamelCase, but if we insist, i think preCICE.jl would not break anything. But since we export all functions now, Users will only have to put `using PreCICE` and can use all the function without the `PreCICE.-` prefix, so it would hurt the eye only once... smile

Haa okay then, if Julia has a convention for module names we can keep `PreCICE.jl` for the time being unless somebody protests.

**Comment by pavelkharitenko** [comment]
I renamed this repository finally to julia-bindings
